# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Snip < Formula
  desc "SNIP: Search, Navigate, Index, Parse"
  homepage "https://github.com/yindia/snip"
  version "0.0.5"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/yindia/snip/releases/download/v0.0.5/snip_0.0.5_darwin_amd64.tar.gz"
      sha256 "e93001717c2cacf9141b6d19af128d898b5b90408ee92303fd727906ebb6201f"

      def install
        bin.install "snip"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/yindia/snip/releases/download/v0.0.5/snip_0.0.5_darwin_arm64.tar.gz"
      sha256 "220cb6ff35cc9a0c94812170330fa3721ba1f069da282fc5016c376b4d03f77f"

      def install
        bin.install "snip"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/yindia/snip/releases/download/v0.0.5/snip_0.0.5_linux_amd64.tar.gz"
      sha256 "512c968ecc5c8d1bee339ba74fb6e147a40fb18d301e05eb9893cbca554fbb16"
      def install
        bin.install "snip"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/yindia/snip/releases/download/v0.0.5/snip_0.0.5_linux_arm64.tar.gz"
      sha256 "cc6a55f35d67722eaa7d8f8cd0d75ee78062bf11dc1a9e807d97971e11ad3e4b"
      def install
        bin.install "snip"
      end
    end
  end

  test do
    system "#{bin}/snip", "--help"
  end
end
