# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Snip < Formula
  desc "SNIP: Search, Navigate, Index, Parse"
  homepage "https://github.com/yindia/snip"
  version "0.0.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/yindia/snip/releases/download/v0.0.1/snip_0.0.1_darwin_amd64.tar.gz"
      sha256 "74116c065cb1481e4c124d2977ea06fccf3dd5913ec1a95c79aba9c712240246"

      def install
        bin.install "snip"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/yindia/snip/releases/download/v0.0.1/snip_0.0.1_darwin_arm64.tar.gz"
      sha256 "eb44822dcebf09c797cb486cf7b51a374e25879b854c44a3c07fb4e54f53fd71"

      def install
        bin.install "snip"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/yindia/snip/releases/download/v0.0.1/snip_0.0.1_linux_amd64.tar.gz"
      sha256 "9b5369227fa737ee8a3620f73bf2af54abc859f5c09e2e525dd46bd8cdcfa6f9"
      def install
        bin.install "snip"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/yindia/snip/releases/download/v0.0.1/snip_0.0.1_linux_arm64.tar.gz"
      sha256 "8885a22721ccb5e2b7274368819844ea421360431a4213e0e25362c64c72ea2d"
      def install
        bin.install "snip"
      end
    end
  end

  test do
    system "#{bin}/snip", "--help"
  end
end
