# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Snip < Formula
  desc "SNIP: Search, Navigate, Index, Parse"
  homepage "https://github.com/yindia/snip"
  version "0.0.4"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/yindia/snip/releases/download/v0.0.4/snip_0.0.4_darwin_amd64.tar.gz"
      sha256 "f85577a71ebe2d5c45240d59abad449a961a246c5279d2609b41cc276164c0fe"

      def install
        bin.install "snip"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/yindia/snip/releases/download/v0.0.4/snip_0.0.4_darwin_arm64.tar.gz"
      sha256 "1ee49b7705829e80f7569bafee881b38afe336312da5f8052e73ed3c3edbcf7a"

      def install
        bin.install "snip"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/yindia/snip/releases/download/v0.0.4/snip_0.0.4_linux_amd64.tar.gz"
      sha256 "2a658b26bb530170ba81f3961e0e2a72f2f40034f32bf8eb3daae759357cf1c9"
      def install
        bin.install "snip"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/yindia/snip/releases/download/v0.0.4/snip_0.0.4_linux_arm64.tar.gz"
      sha256 "cc90d8b38907b082ca758106eb8c378a9e3cddfb76543d7034a00188a7132b5f"
      def install
        bin.install "snip"
      end
    end
  end

  test do
    system "#{bin}/snip", "--help"
  end
end
